# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.

obj-$(CONFIG_ETH_DESIGNWARE) += designware.o
obj-$(CONFIG_GMAC_ROCKCHIP) += gmac_rockchip.o
obj-y += phy/
