# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2015 Samsung Electronics
# Przemyslaw Marczak <p.marczak@samsung.com>
#

obj-$(CONFIG_ADC) += adc-uclass.o
obj-$(CONFIG_SARADC_ROCKCHIP) += rockchip-saradc.o

