# SPDX-License-Identifier: GPL-2.0+

obj-y					+= pinctrl-uclass.o
obj-$(CONFIG_$(SPL_)PINCTRL_GENERIC)	+= pinctrl-generic.o

obj-$(CONFIG_PINCTRL_APPLE)		+= pinctrl-apple.o
obj-$(CONFIG_PINCTRL_AT91)		+= pinctrl-at91.o
obj-$(CONFIG_PINCTRL_AT91PIO4)		+= pinctrl-at91-pio4.o
obj-$(CONFIG_$(SPL_)PINCTRL_ROCKCHIP)	+= rockchip/

obj-$(CONFIG_PINCTRL_ZYNQMP)	+= pinctrl-zynqmp.o
